module.exports = [
  {
    id: 1,
    titulo_artigo: "Título do Artigo 1",
    autor_artigo: "Nome do Autor do Artigo 1",
    curtida_artigo: 20,
    texto_artigo: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula.",
  },
  {
    id: 2,
    titulo_artigo: "Título do Artigo 2",
    autor_artigo: "Nome do Autor do Artigo 2",
    curtida_artigo: 40,
    texto_artigo: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula.",
  },
  {
    id: 3,
    titulo_artigo: "Título do Artigo 3",
    autor_artigo: "Nome do Autor do Artigo 3",
    curtida_artigo: 80,
    texto_artigo: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius sem. Fusce et felis tincidunt, mollis felis a, interdum nisi. Sed id orci in odio tincidunt tristique sit amet quis est. Phasellus sem quam, gravida id mattis sed, ullamcorper sed mauris. Vestibulum tempor neque commodo enim feugiat, quis posuere tellus lacinia. Aliquam sed purus a sapien ultrices varius id et magna. Phasellus fringilla metus vel feugiat pharetra. Nulla a mi feugiat, laoreet ex ut, accumsan ligula.",
  },
];
